---
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python2-sphinx make
install: true
script:
  - make html
after_success:
  - rm -rf ./src ./roles Makefile ./*.md ./*.yml
  - mv ./build/html/* ./
  - rm -rf ./build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: SUPERSECRET
  keep-history: true
  on:
    branch: master
