---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-travis-ci
  namespace: ns-rootpages
  labels:
    auth: rootpages
subjects:
  - kind: ServiceAccount
    name: sa-travis-ci
    namespace: ns-rootpages
roleRef:
  kind: Role
  name: role-travis-ci
  apiGroup: rbac.authorization.k8s.io
