---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-travis-ci
  namespace: ns-rootpages
  labels:
    auth: rootpages
rules:
  - apiGroups:
      - ""
      - "apps"
      - "extensions"
    resources:
      - deployments
      - ingresses
      - pods
      - replicasets
      - services
    verbs:
      - "*"
