---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ing-rootpages
  namespace: ns-rootpages
  labels:
    app: rootpages
  annotations:
    cert-manager.io/cluster-issuer: "clusterissuer-letsencrypt-production"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.org/rewrites: "serviceName=svc-rootpages-main rewrite=/;serviceName=svc-rootpages-stable rewrite=/"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rootpages.lukeshort.cloud
      secretName: secret-tls-rootpages-lukeshort-cloud
  rules:
    - host: rootpages.lukeshort.cloud
      http:
        paths:
          - backend:
              service:
                name: svc-rootpages-stable
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: svc-rootpages-stable
                port:
                  number: 80
            path: /stable
            pathType: Prefix
          - backend:
              service:
                name: svc-rootpages-main
                port:
                  number: 80
            path: /latest
            pathType: Prefix
