---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ing-rootpages
  namespace: ns-rootpages
  labels:
    app: rootpages
spec:
  ingressClassName: nginx
  rules:
    - host: rootpages.lukeshort.cloud
      http:
        paths:
          - backend:
              service:
                name: svc-rootpages
                port:
                  number: 80
            path: /
            pathType: Prefix
