---
- name: Cloning the "master" branch of Root Pages
  git:
    repo: git@github.com:ekultails/rootpages.git
    dest: "{{ tmp_dir }}/rootpages_master"
    version: master
    depth: 1

- name: Cloning the "gh-pages" branch of Root Pages
  git:
    repo: git@github.com:ekultails/rootpages.git
    dest: "{{ tmp_dir }}/rootpages_gh_pages"
    version: gh-pages
    depth: 1

- name: Building the HTML pages from "master"
  shell: SPHINXBUILD="sphinx-build-3" make html
  args:
    chdir: "{{ tmp_dir }}/rootpages_master"

- name: Deleting the old "gh-pages" branch content
  # Delete all files except for these three:
  # ".git", ".", and ".."
  # The last two will throw a false-positive error from the 
  # rm command if they are not excluded.
  shell: "rm -rf '{{ tmp_dir }}/rootpages_gh_pages/!(.git|.|..)'"

- name: Copying over the new HTML content to the "gh-pages" branch
  synchronize:
    src: "{{ tmp_dir }}/rootpages_master/build/html/"
    dest: "{{ tmp_dir }}/rootpages_gh_pages/"
    rsync_opts:
      - "--exclude=.git"

- debug:
    msg: "Review the contents of {{ tmp_dir }}/rootpages_gh_pages/ before manually commiting to the gh-pages branch"
