---
name: Build documentation
on:
  push:
    # Build but do not publish for all development branches that may become pull requests.
    branches:
      - '*'
      - '!main'
      - '!stable'
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Install Sphinx dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-sphinx python3-sphinx-rtd-theme
      - name: Verify that the build works
        run: make html
